build(manager): 👷 upgrade packages to fix manager's local build (#1101)
In this PR, I fixed two build errors when starting manager locally on macOS:

1. **Cannot find python** (caused by out-dated `electron-builder`)

> ```
> $ BUILD_ENV=development npm run action server_manager/electron_app/start mac
> ...
> + electron-builder --mac --config.mac.icon=icons/mac/icon.icns --projectDir=build/server_manager/electron_app/static --config.asarUnpack=server_manager/web_app/images --publish=never '--config.artifactName="Outline-Manager.${ext}"'
> ...
>     ⨯ Exit code: ENOENT. spawn /usr/bin/python ENOENT
> ...
> ```

2. **Cannot run `serve`** (caused by out-dated `webpack-cli`)

> ```
> $ npm run action server_manager/web_app/start
> ...
> TypeError: Class constructor ServeCommand cannot be invoked without 'new'
> ...
> ```

I also added [`@webpack-cli/serve`](https://www.npmjs.com/package/@webpack-cli/serve) as a global package because it is required by `webpack-cli`] when you run `npm run action server_manager/web_app/start`:

```
$ npm run action server_manager/web_app/start
...
Would you like to install serve? (That will run npm install -D @webpack-cli/serve) (yes/NO) : 
@webpack-cli/serve needs to be installed in order to run the command.
...
```